# Generated by Django 3.0.9 on 2020-08-11 10:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('activity', '0004_auto_20200811_0859'),
        ('usergroups', '0002_auto_20200811_1015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usergroup',
            name='admin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='owned_groups', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='usergroup',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='activity.Category'),
        ),
        migrations.AlterField(
            model_name='usergroup',
            name='max_members',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
