# Generated by Django 3.0.9 on 2020-08-11 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usergroups', '0005_application'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='message',
            field=models.CharField(max_length=250),
        ),
    ]
