# Generated by Django 3.0.9 on 2020-08-11 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usergroups', '0006_auto_20200811_1536'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('pending', 'Ausstehend'), ('accepted', 'Angenommen'), ('declined', 'Abgelehnt')], default='pending', max_length=15),
        ),
    ]
