# Generated by Django 3.0.9 on 2020-08-12 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0004_auto_20200811_0859'),
        ('usergroups', '0007_application_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='application',
            options={'ordering': ('status',)},
        ),
        migrations.AlterUniqueTogether(
            name='usergroup',
            unique_together={('name', 'category')},
        ),
    ]
