# Generated by Django 3.0.9 on 2020-08-12 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usergroups', '0009_vacancy_location_component'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='location_component_value',
            field=models.CharField(default='Osnabrück', max_length=40),
            preserve_default=False,
        ),
    ]
