# Generated by Django 3.1 on 2020-08-16 21:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('usergroups', '0010_vacancy_location_component_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='description',
            field=models.CharField(help_text='1-2 Wörter', max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='vacancy',
            unique_together={('user', 'group')},
        ),
    ]
