# Generated by Django 3.1 on 2020-08-21 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usergroups', '0011_auto_20200816_2146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='description',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
