# Generated by Django 3.1 on 2020-10-08 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usergroups', '0012_auto_20200821_0758'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='vacancy',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='vacancy',
            name='group',
        ),
        migrations.RemoveField(
            model_name='vacancy',
            name='user',
        ),
        migrations.DeleteModel(
            name='Application',
        ),
        migrations.DeleteModel(
            name='Vacancy',
        ),
    ]
