# Generated by Django 3.0.9 on 2020-08-11 16:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20200811_0951'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='latest_group_check',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
