# Generated by Django 3.0.9 on 2020-08-12 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0001_initial'),
        ('account', '0003_user_latest_group_check'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='cancelled_appointments',
            field=models.ManyToManyField(related_name='cancellations', to='scheduling.Appointment'),
        ),
        migrations.AddField(
            model_name='user',
            name='confirmed_appointments',
            field=models.ManyToManyField(related_name='participants', to='scheduling.Appointment'),
        ),
    ]
