# Generated by Django 3.1 on 2020-08-17 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_auto_20200814_1221'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='friendrequest',
            unique_together={('requesting_user', 'requested_user')},
        ),
    ]
