# Generated by Django 3.1 on 2020-08-20 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_auto_20200817_2048'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='latest_group_check',
        ),
    ]
