# Generated by Django 3.1 on 2020-08-20 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_remove_user_latest_group_check'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
