# Generated by Django 3.1 on 2020-08-21 09:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_user_profile_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='latest_message_check',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
