# Generated by Django 3.1 on 2020-08-21 10:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_user_latest_message_check'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='latest_group_check',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
