# Generated by Django 3.1 on 2020-08-21 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_user_latest_group_check'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='latest_group_check',
        ),
    ]
