# Generated by Django 3.0.9 on 2020-08-08 15:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('actions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='action',
            name='user',
        ),
        migrations.AddField(
            model_name='action',
            name='source_ct',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='source_obj', to='contenttypes.ContentType'),
        ),
        migrations.AddField(
            model_name='action',
            name='source_id',
            field=models.PositiveIntegerField(blank=True, db_index=True, null=True),
        ),
    ]
