# Generated by Django 3.0.9 on 2020-08-08 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0002_auto_20200808_1509'),
    ]

    operations = [
        migrations.RenameField(
            model_name='action',
            old_name='description',
            new_name='verb',
        ),
    ]
