# Generated by Django 3.1 on 2020-08-15 09:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usergroups', '0010_vacancy_location_component_value'),
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='logentry',
            options={'ordering': ('created',)},
        ),
        migrations.AlterField(
            model_name='logentry',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_log_entries', to='usergroups.usergroup'),
        ),
    ]
