# Generated by Django 3.1 on 2020-08-15 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usergroups', '0010_vacancy_location_component_value'),
        ('chat', '0002_auto_20200815_0959'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LogEntry',
            new_name='ChatLogEntry',
        ),
    ]
