# Generated by Django 3.1 on 2020-10-08 14:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
        ('chat', '0003_auto_20200815_1001'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatCheck',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='chatlogentry',
            name='group',
        ),
        migrations.AddField(
            model_name='chatlogentry',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_messages', to='account.user'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='ChatRoom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_id', models.PositiveIntegerField(db_index=True)),
                ('members', models.ManyToManyField(related_name='chat_rooms', through='chat.ChatCheck', to=settings.AUTH_USER_MODEL)),
                ('target_ct', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'unique_together': {('target_ct', 'target_id')},
            },
        ),
        migrations.AddField(
            model_name='chatcheck',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='last_checks', to='chat.chatroom'),
        ),
        migrations.AddField(
            model_name='chatcheck',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='last_chat_checks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='chatlogentry',
            name='chat_room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='log_entries', to='chat.chatroom'),
            preserve_default=False,
        ),
    ]
