# Generated by Django 3.1 on 2020-08-19 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wall', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='media_mime_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
