# Generated by Django 3.1 on 2020-08-20 15:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0004_auto_20200811_0859'),
        ('wall', '0003_auto_20200820_1533'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='activity.category'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='activity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='activity.activity'),
        ),
    ]
