# Generated by Django 3.1 on 2020-08-20 21:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usergroups', '0011_auto_20200816_2146'),
        ('wall', '0004_auto_20200820_1548'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='author_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='usergroups.usergroup'),
        ),
    ]
