# Generated by Django 3.1 on 2020-08-20 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wall', '0005_post_author_group'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='author_group',
            new_name='group',
        ),
    ]
