# Generated by Django 3.1 on 2020-10-08 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wall', '0006_auto_20200820_2150'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('-created',)},
        ),
    ]
