# Generated by Django 3.0.9 on 2020-08-10 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='type',
        ),
    ]
