# Generated by Django 3.1 on 2020-10-08 14:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0012_auto_20201008_1443'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
        ('activity', '0004_auto_20200811_0859'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tournaments', to='activity.activity')),
                ('location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tournaments', to='account.location')),
            ],
        ),
        migrations.CreateModel(
            name='Opponent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.FloatField(default=0.0)),
                ('position', models.CharField(blank=True, max_length=50, null=True)),
                ('instance_id', models.PositiveIntegerField(db_index=True)),
                ('target_id', models.PositiveIntegerField(db_index=True)),
                ('instance_ct', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opponent_target_ct', to='contenttypes.contenttype')),
                ('target_ct', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_team_match', models.BooleanField(default=False)),
                ('start_time', models.DateTimeField()),
                ('location', models.CharField(max_length=30)),
                ('format', models.CharField(max_length=250)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='activity.activity')),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_matches', to=settings.AUTH_USER_MODEL)),
                ('tournament', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='competitions.tournament')),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='games', to='competitions.match')),
            ],
        ),
    ]
