# Generated by Django 3.0.9 on 2020-08-08 13:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('activity', '0003_auto_20200808_1321'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('name',), 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterField(
            model_name='activity',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='activities', to=settings.AUTH_USER_MODEL),
        ),
    ]
