# Generated by Django 3.0.9 on 2020-08-08 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0004_auto_20200808_1341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='description',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
