# Generated by Django 3.0.9 on 2020-08-09 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0007_auto_20200808_1344'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='created',
        ),
    ]
